### ISSUE TITLE
Multiple defstructs

### ISSUE THREAD

**Issue by JesterXL** [expede/algae#22]
Elixir n00b, bear with me. I put these 2 in my module:

```elixir
defdata do
    East :: String.t()
    West :: String.t()
end

defdata do
    Dev :: String.t()
    Qa :: String.t()
    Prod :: String.t()
end
```

But it fails with:
```shell
== Compilation error in file lib/aws/types.ex ==
** (ArgumentError) defstruct has already been called for SDP.AWS.Types, defstruct can only be called once per module
    lib/aws/types.ex:35: (module)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

If I only put 1, it's fine. Should I just put each one of these in their own module per file?

**Comment by OvermindDL1** [comment]
> If I only put 1, it's fine. Should I just put each one of these in their own module per file?

They need to be in their own modules yes (just like the elixir's default `defstruct`), but they don't need to be in their own files, you could do something like:

```elixir
defmodule SDP.AWS.Types do
  defmodule Directions do
    defdata do
      East :: String.t()
      West :: String.t()
    end
  end

  defmodule MathStuff do
    defdata do
      Dev :: String.t()
      Qa :: String.t()
      Prod :: String.t()
    end
  end
end
```

:-)

**Comment by JesterXL** [comment]
Oh, dude, that's so much better in 1 file, cool, thanks a lot!

**Comment by OvermindDL1** [comment]
Do note, `defdata`, though not `defstruct` and others, supports a shorthand.  This:

```elixir
defmodule SDP.AWS.Types do
  defmodule Directions do
    defdata do
      East :: String.t()
      West :: String.t()
    end
  end

  defmodule MathStuff do
    defdata do
      Dev :: String.t()
      Qa :: String.t()
      Prod :: String.t()
    end
  end
end
```

Is equal to this:

```elixir
defmodule SDP.AWS.Types do
  defdata Directions do
    East :: String.t()
    West :: String.t()
  end

  defdata MathStuff do
    Dev :: String.t()
    Qa :: String.t()
    Prod :: String.t()
  end
end
```

By putting the name as the first argument, before the body, of `defdata` then it implicitly/internally wraps it in a `defmodule` for you.  However you cannot then put functions and such in it sadly, so that only works when you are defining types as I recall.

**Comment by JesterXL** [comment]
That's totally fine, just doing types as I learn. Really helpful, appreciate it!

**Comment by JesterXL** [comment]
Weird, I tried that, but it doesn't work in 1.5 or 1.6 (using kiex). I'm using alias to import it.

**Comment by OvermindDL1** [comment]
What code doesn't work precisely?

**Comment by JesterXL** [comment]
Sorry, that shorter version you gave me, she's yelling about compilation errors. I tried in both 1.5 and 1.6, it only likes the longer version. Lemme retry...

**Comment by JesterXL** [comment]
Ah nevermind, I'm doing `defsum`.

So this works. Can I make it smaller?

```elixir
defmodule SDP.AWS.Types do
  defmodule AWSEnvironment do
    defsum do
      defdata Dev :: none()
      defdata QA :: none()
      defdata Prod :: none()
    end
  end

  defmodule AWSRegion do
    defsum do
      defdata East :: none()
      defdata West :: none()
    end
  end
end
```

**Comment by OvermindDL1** [comment]
> So this works. Can I make it smaller?

Don't think so, that looks minimized (though you can create a macro to shrink it more if you really want).  :-)

**Comment by JesterXL** [comment]
Cool.
